[package]
name = "ws_tcp"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.6", features = ["postgres", "runtime-tokio-native-tls", "macros"] }
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15"

